version: '3'

services:
  gp-flux:
    image: anq12/gp-flux
    env_file:
     - ./gp-flux.env
    volumes:
      - type: bind
        source: ./certificates
        target: /opt/gp-flux/certificates-compose
      - type: bind
        source: ./userlist
        target: /opt/gp-flux/userlist
    build: ../
    privileged: true