version: '3'

services:
  gp-flux:
    image: anq12/gp-flux
    env_file:
     - ./gp-flux.env
    volumes:
      - type: bind
        source: ./certificates
        target: /opt/gp-flux/certificates
      - type: bind
        source: ./docker-compose
        target: /opt/gp-flux/compose     
    build: .
    privileged: true